(function(){
'use strict';
var GROQ_KEY='kopeyka_groq_key',GROQ_URL='https://api.groq.com/openai/v1/chat/completions',MODEL='openai/gpt-oss-20b';
function getKey(){try{return(localStorage.getItem(GROQ_KEY)||'').trim();}catch(e){return '';}}
function setKey(key){try{key=String(key||'').trim();if(key)localStorage.setItem(GROQ_KEY,key);else localStorage.removeItem(GROQ_KEY);}catch(e){}}
function hasKey(){return !!getKey();}
function norm(s){return String(s||'').toLowerCase().replace(/ё/g,'е').replace(/[^a-zа-я0-9\s]+/gi,' ').replace(/\s+/g,' ').trim();}
function n(v){var x=Number(v);return isFinite(x)?Math.round(x):0;}
function fmt(v){return n(v).toLocaleString('ru-RU')+' ₽';}
function getContext(){try{return window.kopeykaEngine&&typeof window.kopeykaEngine.context==='function'?window.kopeykaEngine.context():JSON.stringify(window.STATE||{});}catch(e){return '{}';}}
function parseResponse(raw){var text=String(raw||'').trim().replace(/^```json\s*/i,'').replace(/^```\s*/i,'').replace(/\s*```$/i,'');var start=text.indexOf('{'),end=text.lastIndexOf('}');if(start>=0&&end>start)text=text.slice(start,end+1);var result=JSON.parse(text);if(!result||typeof result!=='object')throw new Error('Неверный ответ ИИ');if(!Array.isArray(result.actions))result.actions=[];return result;}
function debts(){return(window.STATE&&Array.isArray(window.STATE.debts))?window.STATE.debts:[];}
function obligations(){return(window.STATE&&Array.isArray(window.STATE.obligations))?window.STATE.obligations:[];}
function resolveDebt(name){var q=norm(name),arr=debts();if(!q)return null;var exact=arr.find(function(d){return norm(d.name)===q;});if(exact)return exact;var tokens=q.split(' ').filter(Boolean);return arr.find(function(d){var dn=norm(d.name);return tokens.some(function(t){return dn===t||dn.indexOf(t)===0||t.indexOf(dn)===0;});})||null;}
function resolveObligation(name,amount){var arr=obligations(),a=n(amount);if(a>0){var byAmount=arr.filter(function(x){return x.active!==false&&n(x.amount)===a;});if(byAmount.length===1)return byAmount[0];}var q=norm(name);if(!q)return null;return arr.find(function(x){return x.active!==false&&norm(x.name)===q;})||arr.find(function(x){var xn=norm(x.name);return q.split(' ').some(function(t){return t&& (xn.indexOf(t)===0||t.indexOf(xn)===0);});})||null;}
function normalizeActions(result){if(!result||!Array.isArray(result.actions))return result;result.actions=result.actions.map(function(a){if(!a||typeof a!=='object')return a;if(a.type==='add_expense'){var nm=String(a.name||'').trim();var q=norm(nm);if(q.indexOf('зубн')===0&&q.indexOf('щет')>=0)nm='Зубная щётка';if(q.indexOf('футбол')===0&&q.indexOf('мяч')>=0)nm='Футбольный мяч';a.name=nm;if(window.kopeykaEngine&&window.kopeykaEngine.classifyName)a.category=window.kopeykaEngine.classifyName(nm,a.category);}if(a.type==='increase_debt'||a.type==='pay_debt'||a.type==='delete_debt'){var d=resolveDebt(a.name);if(d)a.name=d.name;}if(a.type==='delete_obligation'){var o=resolveObligation(a.name,a.amount);if(o){a.name=o.name;a.amount=n(o.amount);a.id=o.id;}}return a;});return result;}
function localIntent(text){var t=norm(text),m,amount,name;
 if(/^(сколько|какие|что)\b/.test(t)&&/(расход|потрат)/.test(t)&&/(прошл|предыдущ)/.test(t)){var cur=window.kopeykaEngine&&window.kopeykaEngine.getSelectedMonth?window.kopeykaEngine.getSelectedMonth():new Date().toISOString().slice(0,7),p=cur.split('-').map(Number),pm=p[1]-1,py=p[0];if(pm<1){pm=12;py--;}var c=window.kopeykaEngine&&window.kopeykaEngine.month?window.kopeykaEngine.month(py+'-'+String(pm).padStart(2,'0')):null;if(c)return{mode:'answer',text:'Расходы за прошлый месяц: '+fmt(c.expenses),summary:null,actions:[]};}
 if(/^(сколько|какие|что)\b/.test(t)&&/(доход|заработ|получ)/.test(t)&&/(следующ|будущ)/.test(t)){var cur2=window.kopeykaEngine&&window.kopeykaEngine.getSelectedMonth?window.kopeykaEngine.getSelectedMonth():new Date().toISOString().slice(0,7),p2=cur2.split('-').map(Number),nm=p2[1]+1,ny=p2[0];if(nm>12){nm=1;ny++;}var c2=window.kopeykaEngine&&window.kopeykaEngine.month?window.kopeykaEngine.month(ny+'-'+String(nm).padStart(2,'0')):null;if(c2)return{mode:'answer',text:'Доходы за следующий месяц: '+fmt(c2.income),summary:null,actions:[]};}
 m=t.match(/(?:купил|купила|потратил|потратила|куплено|расход)\s+(.+?)\s+(?:за|на)\s+(\d[\d\s]*(?:[.,]\d+)?)/);if(m){name=m[1].trim();amount=n(String(m[2]).replace(/\s/g,'').replace(',','.'));if(amount>0)return{mode:'action',text:null,summary:'Добавить расход',actions:[{type:'add_expense',amount:amount,name:name,category:window.kopeykaEngine&&window.kopeykaEngine.classifyName?window.kopeykaEngine.classifyName(name,'Прочее'):'Прочее',date:new Date().toISOString().slice(0,10)}]};}
 m=t.match(/(?:увеличь|увеличить|добавь)\s+(?:долг\s+)?(.+?)\s+(?:на|на сумму)\s+(\d[\d\s]*)/);if(m&&/долг/.test(t)){var d=resolveDebt(m[1]);amount=n(m[2].replace(/\s/g,''));if(d&&amount>0)return{mode:'action',text:null,summary:'Увеличить долг «'+d.name+'» на '+fmt(amount),actions:[{type:'increase_debt',name:d.name,amount:amount}]};}
 m=t.match(/(?:удали|удалить|убери|убрать)\s+(?:обязательный\s+платеж|обязательный платеж|платеж)\s*(?:на|в размере)?\s*(\d[\d\s]*)/);if(m){amount=n(m[1].replace(/\s/g,''));var o=resolveObligation('',amount);if(o)return{mode:'action',text:null,summary:'Удалить обязательный платёж «'+o.name+'»',actions:[{type:'delete_obligation',name:o.name,amount:n(o.amount),id:o.id}]};}
 return null;}
function askConversation(history,userText){var local=localIntent(userText);if(local)return Promise.resolve(local);return new Promise(function(resolve,reject){var key=getKey();if(!key){reject(new Error('Нет ключа Groq. Открой настройки Копейки и укажи ключ Groq.'));return;}
 var system=['Ты — Копейка AI, финансовый ассистент приложения. Отвечай только по-русски.','АКТУАЛЬНОЕ СОСТОЯНИЕ содержит полные массивы income, expenses, debts, reserves, obligations, reserveOps и obligationPays за все доступные даты, а monthlyCalculations содержит предыдущий, выбранный и следующий месяцы, даже если в них ноль.','Никогда не утверждай, что не видишь предыдущий или следующий месяц, если он присутствует в контексте.','Для финансовой математики используй готовые calculations и monthlyCalculations.','Для расходов сохраняй реальное название покупки. «зубная щётка» — название, категория Хозтовары. «футбольный мяч» — название, категория Развлечения.','Имена долгов и обязательных платежей сопоставляй без учёта регистра, ё/е и русского падежа. «Ёжик», «Ёжику», «Ёжика», «Ёжиком» — один объект.','Для удаления обязательного платежа на указанную сумму ищи существующий объект obligations по amount.','Для изменения существующего долга используй его существующее имя из debts.','Если пользователь спрашивает о синхронизации, отвечай по cloud.online, cloud.connected и cloud.status.','Если пользователь просит изменить данные, верни действие. Изменения выполняются только после подтверждения интерфейсом.','Ответ строго JSON без markdown. Формат: {"mode":"answer","text":"...","summary":null,"actions":[]} или {"mode":"action","text":null,"summary":"...","actions":[...]}.','Допустимые действия: add_expense, add_income, add_debt, pay_debt, increase_debt, reserve_deposit, reserve_withdraw, add_obligation, delete_debt, delete_income, delete_expense, delete_reserve, delete_obligation, delete_last, change_last, set_opening_balance, set_day_rate, set_night_rate, change_shift.'].join('\n');
 var messages=[{role:'system',content:system+'\n\nПОЛНЫЙ КОНТЕКСТ КОПЕЙКИ:\n'+getContext()}];(history||[]).slice(-12).forEach(function(item){messages.push({role:item.role==='assistant'?'assistant':'user',content:String(item.content||'')});});messages.push({role:'user',content:String(userText||'')});var controller=typeof AbortController!=='undefined'?new AbortController():null,timer=setTimeout(function(){try{if(controller)controller.abort();}catch(e){}reject(new Error('Groq не ответил за 20 секунд'));},20000);fetch(GROQ_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+key},body:JSON.stringify({model:MODEL,temperature:0.05,max_completion_tokens:1400,messages:messages}),signal:controller?controller.signal:undefined}).then(function(response){return response.text().then(function(body){clearTimeout(timer);var data;try{data=JSON.parse(body);}catch(e){throw new Error('Groq вернул некорректный ответ ('+response.status+')');}if(!response.ok){var message=data&&data.error&&data.error.message?data.error.message:('HTTP '+response.status);if(response.status===401)message='Неверный ключ Groq';if(response.status===429)message='Лимит Groq временно исчерпан';throw new Error(message);}var content=data&&data.choices&&data.choices[0]&&data.choices[0].message&&data.choices[0].message.content;if(!content)throw new Error('Пустой ответ Groq');resolve(normalizeActions(parseResponse(content)));});}).catch(function(error){clearTimeout(timer);if(error&&error.name==='AbortError')reject(new Error('Таймаут Groq'));else if(error&&/Failed to fetch/i.test(error.message||''))reject(new Error('Нет сети или api.groq.com недоступен'));else reject(error);});});}
function askAgent(text){return askConversation([],text);}function ask(text){return askAgent(text).then(function(result){return result.mode==='answer'?(result.text||''):(result.summary||result.text||'');});}function testKey(){return askAgent('Ответь одним словом: готово').then(function(){return 'Ключ работает ✓';});}
window.kopeykaAI={getKey:getKey,setKey:setKey,hasKey:hasKey,ask:ask,askAgent:askAgent,askConversation:askConversation,testKey:testKey,buildContext:getContext};
})();
