(function(){
'use strict';
var GROQ_KEY='kopeyka_groq_key',GROQ_URL='https://api.groq.com/openai/v1/chat/completions',MODEL='openai/gpt-oss-20b';
function getKey(){try{return(localStorage.getItem(GROQ_KEY)||'').trim();}catch(e){return'';}}
function setKey(k){try{k=String(k||'').trim();if(k)localStorage.setItem(GROQ_KEY,k);else localStorage.removeItem(GROQ_KEY);}catch(e){}}
function hasKey(){return!!getKey();}
function context(){if(window.kopeykaEngine&&window.kopeykaEngine.context)return window.kopeykaEngine.context();return JSON.stringify(window.STATE||{});}
function systemPrompt(){return 'Ты — Копейка AI, встроенный финансовый ассистент. Ты понимаешь русский язык, разговорные формулировки, сленг и опечатки. Ты видишь ПОЛНОЕ актуальное состояние приложения и точные расчёты финансового движка. Никогда не придумывай цифры, операции, долги, резервы или даты. Для чисел используй calculations из состояния, а не собственные вычисления. Особенно: «сколько могу потратить сегодня» = calculations.dailyBudget. «сколько осталось» = calculations.available. Учитывай selectedMonth.\n\nВАЖНО: ты только интерпретируешь запрос и предлагаешь действие. Изменения выполняет приложение после подтверждения пользователя.\n\nОтвет ВСЕГДА JSON: обычный ответ: {"mode":"answer","text":"...","summary":null,"actions":[]}; действие: {"mode":"action","text":null,"summary":"...","actions":[{"type":"...","amount":0,"name":null,"category":null,"reserve":null,"day":null,"date":null,"shift":null,"target":null}]}.\n\nДействия: add_expense, add_income, add_debt, pay_debt, increase_debt, reserve_deposit, reserve_withdraw, add_obligation, delete_debt, delete_income, delete_expense, delete_reserve, delete_obligation, delete_last, change_last, set_opening_balance, set_day_rate, set_night_rate, change_shift.\n\nРасход: «купил майонез 500» → add_expense, amount 500, name «Майонез», category «Продукты». «купил сигареты 500» → name «Сигареты», category «Сигареты». Не записывай исходную фразу целиком в name.\n\n«дать к долгу папе 189», «отдал папе 189», «внёс в долг папа 189» → pay_debt, а не add_expense. «добавь долг папа 5000» → add_debt. «увеличь долг папа на 500» → increase_debt. Для имени используй ближайшее существующее имя из debts. Аналогично резервы.\n\nКатегории: Продукты, Алкоголь, Сигареты, Хозтовары, Бытовая химия, Кафе, Связь, Проезд, Жильё, Здоровье, Красота, Одежда, Развлечения, Подписки, Техника, Дети, Животные, Обязательные, Долг, Прочее.\n\nЕсли пользователь просит удалить/изменить конкретную запись, сначала найди её в полном состоянии. Если однозначности нет — задай уточняющий вопрос вместо опасного действия. Если пользователь просто спрашивает — mode answer. Отвечай по-русски, кратко и точно.';}
var schema={type:'json_schema',json_schema:{name:'kopeyka_response',strict:true,schema:{type:'object',additionalProperties:false,properties:{mode:{type:'string',enum:['answer','action']},text:{type:['string','null']},summary:{type:['string','null']},actions:{type:'array',items:{type:'object',additionalProperties:false,properties:{type:{type:'string',enum:['add_expense','add_income','add_debt','pay_debt','increase_debt','reserve_deposit','reserve_withdraw','add_obligation','delete_debt','delete_income','delete_expense','delete_reserve','delete_obligation','delete_last','change_last','set_opening_balance','set_day_rate','set_night_rate','change_shift']},amount:{type:['number','null']},name:{type:['string','null']},category:{type:['string','null']},reserve:{type:['string','null']},day:{type:['number','null']},date:{type:['string','null']},shift:{type:['string','null']},target:{type:['string','null']}},required:['type','amount','name','category','reserve','day','date','shift','target']}}},required:['mode','text','summary','actions']}};
function parse(raw){var t=String(raw||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');var a=t.indexOf('{'),b=t.lastIndexOf('}');if(a>=0&&b>a)t=t.slice(a,b+1);var o=JSON.parse(t);if(!o||typeof o!=='object')throw new Error('Неверный ответ ИИ');if(!Array.isArray(o.actions))o.actions=[];return o;}
function askConversation(history,userText){return new Promise(function(resolve,reject){var key=getKey();if(!key){reject(new Error('Нет ключа Groq. Открой ⚙ → Ключ Groq.'));return;}var messages=[{role:'system',content:systemPrompt()+'\n\nПОЛНОЕ СОСТОЯНИЕ И ТОЧНЫЕ РАСЧЁТЫ:\n'+context()}];(history||[]).slice(-16).forEach(function(m){messages.push({role:m.role==='assistant'?'assistant':'user',content:String(m.content||'')});});messages.push({role:'user',content:String(userText||'')});var ctrl=typeof AbortController!=='undefined'?new AbortController():null,timer=setTimeout(function(){try{ctrl&&ctrl.abort();}catch(e){}reject(new Error('Groq не ответил за 20 секунд'));},20000);var body={model:MODEL,temperature:0.05,max_completion_tokens:1600,response_format:schema,messages:messages};var opts={method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+key},body:JSON.stringify(body)};if(ctrl)opts.signal=ctrl.signal;fetch(GROQ_URL,opts).then(function(r){return r.text().then(function(txt){clearTimeout(timer);var j;try{j=JSON.parse(txt);}catch(e){throw new Error('Groq вернул не JSON ('+r.status+')');}if(!r.ok){var msg=j&&j.error&&j.error.message||('HTTP '+r.status);if(r.status===401)msg='Неверный ключ Groq';if(r.status===429)msg='Лимит Groq временно исчерпан';throw new Error(msg);}var c=j&&j.choices&&j.choices[0]&&j.choices[0].message&&j.choices[0].message.content;if(!c)c=j&&j.choices&&j.choices[0]&&j.choices[0].message&&j.choices[0].message.content;if(!c)throw new Error('Пустой ответ Groq');resolve(parse(c));});}).catch(function(e){clearTimeout(timer);if(e&&e.name==='AbortError')reject(new Error('Таймаут'));else if(e&&/Failed to fetch/i.test(e.message||''))reject(new Error('Нет сети или заблокирован api.groq.com'));else reject(e);});});}
function askAgent(text){return askConversation([],text);}
function ask(text){return askAgent(text).then(function(o){return o.mode==='answer'?(o.text||''):(o.summary||o.text||'');});}
function testKey(){return askAgent('Ответь кратко: готово').then(function(){return'Ключ работает ✓';});}
window.kopeykaAI={getKey:getKey,setKey:setKey,hasKey:hasKey,ask:ask,askAgent:askAgent,askConversation:askConversation,testKey:testKey,buildContext:context};
})();
