(function(){
'use strict';
if(window.__kopeykaAssistantLoaded)return;window.__kopeykaAssistantLoaded=true;
var SR=window.SpeechRecognition||window.webkitSpeechRecognition;
var history=[],pending=null,rec=null,listening=false,closed=false;
var CATS=['Продукты','Алкоголь','Сигареты','Хозтовары','Бытовая химия','Кафе','Связь','Проезд','Жильё','Здоровье','Красота','Одежда','Развлечения','Подписки','Техника','Дети','Животные','Обязательные','Долг','Прочее'];
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7);}
function n(v){var x=Number(v);return isFinite(x)?Math.round(x):0;}
function norm(s){return String(s||'').toLowerCase().replace(/ё/g,'е').trim();}
function fmt(v){return n(v).toLocaleString('ru-RU')+' ₽';}
function today(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function open(){if(document.getElementById('kopeykaAiDialog'))return;closed=false;document.body.insertAdjacentHTML('beforeend','<div id="kopeykaAiDialog" class="ka-bg"><div class="ka-card"><div class="ka-head"><div><div class="ka-kicker">Копейка AI</div><div class="ka-title">Финансовый помощник</div></div><button class="ka-close" id="kaClose">×</button></div><div class="ka-chat" id="kaChat"><div class="ka-empty" id="kaEmpty">Нажми на круг и говори.<br>Я вижу данные Копейки и могу отвечать на вопросы и управлять ими.</div></div><button class="ka-orb" id="kaOrb" aria-label="Говорить"><span>●</span></button><div class="ka-status" id="kaStatus">Нажми на круг, чтобы говорить</div><div class="ka-input-row"><input id="kaInput" placeholder="Или напиши сообщение…"><button id="kaSend">➤</button></div></div></div>');style();document.getElementById('kaClose').onclick=close;document.getElementById('kaOrb').onclick=toggleListen;document.getElementById('kaSend').onclick=function(){var x=document.getElementById('kaInput').value.trim();if(x){document.getElementById('kaInput').value='';handle(x);}};document.getElementById('kaInput').addEventListener('keydown',function(e){if(e.key==='Enter'){var x=this.value.trim();if(x){this.value='';handle(x);}}});}
function close(){closed=true;stopListen();var e=document.getElementById('kopeykaAiDialog');if(e)e.remove();}
function style(){if(document.getElementById('kaStyle'))return;var s=document.createElement('style');s.id='kaStyle';s.textContent='.ka-bg{position:fixed;inset:0;z-index:1000;background:rgba(0,0,0,.72);display:flex;align-items:flex-end;justify-content:center}.ka-card{width:100%;max-width:560px;height:min(92vh,760px);background:#111318;color:#f2f3f7;border:1px solid rgba(255,255,255,.1);border-radius:24px 24px 0 0;display:flex;flex-direction:column;padding:16px 14px calc(14px + env(safe-area-inset-bottom,0px));box-shadow:0 -10px 40px rgba(0,0,0,.45)}.ka-head{display:flex;justify-content:space-between;align-items:flex-start}.ka-kicker{font-size:10px;color:#a1a6b4;text-transform:uppercase;letter-spacing:.08em}.ka-title{font-size:19px;font-weight:700;margin-top:2px}.ka-close{width:38px;height:38px;border-radius:12px;background:#1c1f27;color:#fff;font-size:25px}.ka-chat{flex:1;overflow:auto;padding:14px 2px;display:flex;flex-direction:column;gap:9px}.ka-empty{text-align:center;color:#9298a7;font-size:13px;line-height:1.55;margin:auto 20px}.ka-msg{max-width:88%;padding:10px 12px;border-radius:15px;font-size:14px;line-height:1.45;white-space:pre-wrap}.ka-user{align-self:flex-end;background:#29251d;border:1px solid rgba(229,167,94,.25)}.ka-ai{align-self:flex-start;background:#1b1e26;border:1px solid rgba(255,255,255,.07)}.ka-action{margin-top:8px;padding:11px;border-radius:12px;background:#171a20;border:1px solid rgba(229,167,94,.25)}.ka-actions{display:flex;gap:8px;margin-top:9px}.ka-act{flex:1;padding:11px;border-radius:11px;font-weight:700;background:#242832;color:#fff}.ka-act.ok{background:linear-gradient(135deg,#f0c384,#e5a75e);color:#1a1208}.ka-orb{flex:0 0 auto;width:82px;height:82px;margin:4px auto 7px;border-radius:50%;border:0;background:linear-gradient(135deg,#f0c384,#e5a75e);color:#1a1208;font-size:30px;box-shadow:0 8px 28px rgba(229,167,94,.32)}.ka-orb.listening{animation:kaPulse 1s infinite}.ka-status{text-align:center;color:#969cab;font-size:12px;min-height:18px;margin-bottom:8px}.ka-input-row{display:flex;gap:7px}.ka-input-row input{flex:1;min-width:0;background:#1b1e26;border:1px solid rgba(255,255,255,.08);border-radius:12px;padding:11px 12px;color:#fff}.ka-input-row button{width:44px;border-radius:12px;background:#e5a75e;color:#1a1208;font-weight:800}@keyframes kaPulse{50%{transform:scale(1.07);box-shadow:0 0 0 14px rgba(229,167,94,.12)}}';document.head.appendChild(s);}
function bubble(role,text){var c=document.getElementById('kaChat');if(!c)return;var e=document.getElementById('kaEmpty');if(e)e.remove();var d=document.createElement('div');d.className='ka-msg '+(role==='user'?'ka-user':'ka-ai');d.textContent=text;c.appendChild(d);c.scrollTop=c.scrollHeight;}
function setStatus(x){var e=document.getElementById('kaStatus');if(e)e.textContent=x;}
function speak(text){/* silent */}
function toggleListen(){if(listening)stopListen();else startListen();}
function startListen(){if(!SR){setStatus('В этом браузере нет распознавания речи');return;}if(rec)return;rec=new SR();rec.lang='ru-RU';rec.interimResults=false;rec.continuous=false;rec.maxAlternatives=3;rec.onstart=function(){listening=true;document.getElementById('kaOrb').classList.add('listening');setStatus('Слушаю…');};rec.onresult=function(e){var text='';for(var i=0;i<e.results.length;i++)text+=e.results[i][0].transcript+' ';text=text.trim();stopListen();if(text)handle(text);};rec.onerror=function(e){stopListen();setStatus(e.error==='not-allowed'?'Нет доступа к микрофону':'Не удалось распознать речь');};rec.onend=function(){if(listening){listening=false;var o=document.getElementById('kaOrb');if(o)o.classList.remove('listening');}};try{rec.start();}catch(e){stopListen();setStatus('Не удалось запустить микрофон');}}
function stopListen(){if(rec){try{rec.stop();}catch(e){}rec=null;}listening=false;var o=document.getElementById('kaOrb');if(o)o.classList.remove('listening');}
function isConfirm(s){return /^(да|ага|угу|подтверждаю|сделай|выполняй|добавь|верно|правильно|ок|окей|yes|удали)$/i.test(norm(s));}
function isCancel(s){return /^(нет|отмена|отменить|не надо|не делай|стоп)$/i.test(norm(s));}
function handle(text){bubble('user',text);if(pending&&(isConfirm(text)||isCancel(text))){if(isConfirm(text))confirmPending();else cancelPending();return;}setStatus('Думаю…');if(!window.kopeykaAI||!window.kopeykaAI.askConversation){setStatus('Подключаю ИИ…');setTimeout(function(){if(!window.kopeykaAI||!window.kopeykaAI.askConversation){setStatus('ИИ не загрузился. Обнови страницу.');return;}handle(text);},600);return;}var h=history.slice(-12);history.push({role:'user',content:text});window.kopeykaAI.askConversation(h,text).then(function(o){if(o.mode==='action'){pending=o.actions||[];var summary=o.summary||'Нужно выполнить действие';renderAction(summary,pending);}else{var ans=o.text||'Не смогла сформулировать ответ.';history.push({role:'assistant',content:ans});bubble('ai',ans);setStatus('Нажми на круг, чтобы продолжить');}}).catch(function(e){var m=e&&e.message||'Ошибка ИИ';bubble('ai','Не получилось: '+m);setStatus('Ошибка');});}
function renderAction(summary,actions){var c=document.getElementById('kaChat');if(!c)return;var d=document.createElement('div');d.className='ka-msg ka-ai';var box=document.createElement('div');box.className='ka-action';box.textContent=summary;var list=document.createElement('div');list.style.marginTop='8px';actions.forEach(function(a){var x=document.createElement('div');x.textContent=describe(a);list.appendChild(x);});box.appendChild(list);var row=document.createElement('div');row.className='ka-actions';var ok=document.createElement('button');ok.className='ka-act ok';ok.textContent=(actions&&actions[0]&&String(actions[0].type||'').indexOf('delete')===0)?'Удалить':'Подтвердить';ok.onclick=confirmPending;var no=document.createElement('button');no.className='ka-act';no.textContent='Отмена';no.onclick=cancelPending;row.appendChild(ok);row.appendChild(no);box.appendChild(row);d.appendChild(box);c.appendChild(d);c.scrollTop=c.scrollHeight;setStatus('Проверь операцию');}
function describe(a){var t=a&&a.type||'';if(t==='add_expense')return'Расход: '+(a.name||a.category||'Прочее')+' — '+fmt(a.amount);if(t==='add_income')return'Доход: '+(a.name||'доход')+' — +'+fmt(a.amount);if(t==='reserve_deposit')return'В резерв «'+(a.reserve||a.name)+'»: '+fmt(a.amount);if(t==='reserve_withdraw')return'Из резерва «'+(a.reserve||a.name)+'» снять: '+fmt(a.amount);if(t==='add_debt')return'Долг «'+(a.name||'Долг')+'»: '+fmt(a.amount);if(t==='pay_debt')return'Платёж по долгу «'+(a.name||'')+'»: '+fmt(a.amount);if(t==='add_obligation')return'Обязательный «'+(a.name||'Платёж')+'»: '+fmt(a.amount);if(t==='change_last')return'Изменить последнюю на '+fmt(a.amount);if(t==='delete_last')return'Удалить последнюю операцию'+(a.target?' ('+a.target+')':'');if(t==='delete_debt')return'Удалить долг «'+(a.name||'')+'»';if(t==='delete_income')return'Удалить доход «'+(a.name||'последний')+'»';if(t==='delete_expense')return'Удалить расход «'+(a.name||'последний')+'»';if(t==='delete_reserve')return'Удалить резерв «'+(a.name||a.reserve||'')+'»';if(t==='delete_obligation')return'Удалить обязательный «'+(a.name||'')+'»';if(t==='set_opening_balance')return'Начальный остаток: '+fmt(a.amount);return t;}
function clone(){return JSON.parse(JSON.stringify(window.STATE||{}));}
function apply(s){if(typeof window.setAppState!=='function')throw new Error('Копейка ещё не готова');window.setAppState(s);}
function findReserve(s,name){var q=norm(name||'');return(s.reserves||[]).find(function(r){return norm(r.name)===q||norm(r.name).indexOf(q)!==-1||q.indexOf(norm(r.name))!==-1;});}
function execute(a){var s=clone(),t=a.type,amount=n(a.amount);
if(t==='add_expense'){if(amount<=0)throw Error('Сумма расхода должна быть больше нуля');s.expenses=s.expenses||[];s.expenses.push({id:id(),amount:amount,category:CATS.indexOf(a.category)>=0?a.category:'Прочее',note:String(a.name||a.note||a.category||'Расход'),date:today()});}
else if(t==='add_income'){if(amount<=0)throw Error('Сумма дохода должна быть больше нуля');s.income=s.income||[];s.income.push({id:id(),amount:amount,note:String(a.name||a.note||'Доход'),date:today()});}
else if(t==='reserve_deposit'||t==='reserve_withdraw'){s.reserves=s.reserves||[];s.reserveOps=s.reserveOps||[];var r=findReserve(s,a.reserve||a.name);if(!r)throw Error('Резерв не найден');if(amount<=0)throw Error('Сумма должна быть больше нуля');if(t==='reserve_withdraw'&&amount>n(r.saved))throw Error('В резерве только '+fmt(r.saved));r.saved=n(r.saved)+(t==='reserve_deposit'?amount:-amount);s.reserveOps.push({id:id(),reserveId:r.id,type:t==='reserve_deposit'?'deposit':'withdraw',amount:amount,date:today()});}
else if(t==='add_debt'){if(amount<=0)throw Error('Сумма долга должна быть больше нуля');s.debts=s.debts||[];s.debts.push({id:id(),name:String(a.name||'Долг'),total:amount,paid:0});}
else if(t==='pay_debt'){var q=norm(a.name||'');var d=(s.debts||[]).find(function(x){return q&&norm(x.name).indexOf(q)!==-1;})||(s.debts||[]).find(function(x){return n(x.total)>n(x.paid);});if(!d)throw Error('Долг не найден');if(amount<=0||amount>n(d.total)-n(d.paid))throw Error('Некорректная сумма платежа');d.paid=n(d.paid)+amount;s.expenses=s.expenses||[];s.expenses.push({id:id(),amount:amount,category:'Долг',note:d.name,date:today()});}
else if(t==='add_obligation'){if(amount<=0)throw Error('Сумма обязательного платежа должна быть больше нуля');var day=n(a.day||25);if(day<1||day>31)throw Error('День должен быть от 1 до 31');s.obligations=s.obligations||[];s.obligations.push({id:id(),name:String(a.name||'Платёж'),amount:amount,day:day,active:true});}
else if(t==='delete_debt'){var qd=norm(a.name||'');var dd=(s.debts||[]).find(function(x){return qd&&(norm(x.name)===qd||norm(x.name).indexOf(qd)!==-1||qd.indexOf(norm(x.name))!==-1);});if(!dd&&(s.debts||[]).length===1)dd=s.debts[0];if(!dd)throw Error('Долг не найден'+(qd?': '+a.name:''));s.debts=s.debts.filter(function(x){return x.id!==dd.id;});}
else if(t==='delete_income'){var qi=norm(a.name||'');var incItem=null;if(qi){incItem=(s.income||[]).slice().reverse().find(function(x){return norm(x.note||'').indexOf(qi)!==-1;});}if(!incItem&&(s.income||[]).length)incItem=s.income[s.income.length-1];if(!incItem)throw Error('Доход не найден');s.income=s.income.filter(function(x){return x.id!==incItem.id;});}
else if(t==='delete_expense'){var qe=norm(a.name||a.category||'');var exItem=null;if(qe){exItem=(s.expenses||[]).slice().reverse().find(function(x){return norm(x.note||'').indexOf(qe)!==-1||norm(x.category||'').indexOf(qe)!==-1;});}if(!exItem&&(s.expenses||[]).length)exItem=s.expenses[s.expenses.length-1];if(!exItem)throw Error('Расход не найден');s.expenses=s.expenses.filter(function(x){return x.id!==exItem.id;});}
else if(t==='delete_reserve'){var qr=norm(a.name||a.reserve||'');var rr=(s.reserves||[]).find(function(x){return qr&&(norm(x.name).indexOf(qr)!==-1||qr.indexOf(norm(x.name))!==-1);});if(!rr)throw Error('Резерв не найден');s.reserves=s.reserves.filter(function(x){return x.id!==rr.id;});s.reserveOps=(s.reserveOps||[]).filter(function(o){return o.reserveId!==rr.id;});}
else if(t==='delete_obligation'){var qo=norm(a.name||'');var oo=(s.obligations||[]).find(function(x){return qo&&norm(x.name).indexOf(qo)!==-1;});if(!oo)throw Error('Обязательный платёж не найден');s.obligations=s.obligations.filter(function(x){return x.id!==oo.id;});}
else if(t==='delete_last'){var target=String(a.target||a.name||'any').toLowerCase();if(target.indexOf('debt')!==-1||target.indexOf('долг')!==-1){if(!(s.debts||[]).length)throw Error('Нет долгов');var lastD=s.debts[s.debts.length-1];s.debts=s.debts.filter(function(x){return x.id!==lastD.id;});}else if(target.indexOf('income')!==-1||target.indexOf('доход')!==-1){if(!(s.income||[]).length)throw Error('Нет доходов');var lastI=s.income[s.income.length-1];s.income=s.income.filter(function(x){return x.id!==lastI.id;});}else if(target.indexOf('expense')!==-1||target.indexOf('расход')!==-1){if(!(s.expenses||[]).length)throw Error('Нет расходов');var lastE=s.expenses[s.expenses.length-1];s.expenses=s.expenses.filter(function(x){return x.id!==lastE.id;});}else{var ex=s.expenses&&s.expenses.length?s.expenses[s.expenses.length-1]:null;var inc=s.income&&s.income.length?s.income[s.income.length-1]:null;if(!ex&&!inc)throw Error('Нечего удалять');var pe=ex&&(!inc||String(ex.id)>String(inc.id));if(pe)s.expenses=s.expenses.filter(function(x){return x.id!==ex.id;});else s.income=s.income.filter(function(x){return x.id!==inc.id;});}}
else if(t==='change_last'){var ex2=s.expenses&&s.expenses.length?s.expenses[s.expenses.length-1]:null,inc2=s.income&&s.income.length?s.income[s.income.length-1]:null;if(!ex2&&!inc2)throw Error('Нечего менять');if(amount<=0)throw Error('Сумма должна быть больше нуля');var pe2=ex2&&(!inc2||String(ex2.id)>String(inc2.id));if(pe2)ex2.amount=amount;else inc2.amount=amount;}
else if(t==='set_opening_balance'){s.settings=s.settings||{};s.settings.openingBalance=amount;}
else if(t==='set_day_rate'){s.settings=s.settings||{};s.settings.dayRate=amount;}
else if(t==='set_night_rate'){s.settings=s.settings||{};s.settings.nightRate=amount;}
else throw Error('Действие не поддерживается: '+t);
apply(s);}
function confirmPending(){if(!pending)return;var actions=pending.slice();pending=null;try{actions.forEach(execute);var text='Готово. Изменения внесены в Копейку.';history.push({role:'assistant',content:text});bubble('ai',text);setStatus('Готово. Нажми на круг, чтобы продолжить');}catch(e){bubble('ai','Не внесла изменения: '+(e.message||e));setStatus('Ошибка операции');}}
function cancelPending(){pending=null;var text='Отменила. Ничего не изменено.';history.push({role:'assistant',content:text});bubble('ai',text);setStatus('Нажми на круг, чтобы продолжить');}
window.kopeykaAssistant={open:open,close:close};
window.kopeykaVoice=window.kopeykaAssistant;
})();
