/* cloud.js v13 — single-source sync, safe deletes, no RPC fallback */
(function(){
'use strict';
const URL='https://cqslrfphsjllhltsvvuq.supabase.co';
const KEY='sb_publishable_cM_XCycYRFLIc6qEqlH83Q_5XY6kPzG';
const LOCAL_BASE='kopeyka3_state_v1';
const SDK_URL='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.3';

let sb=null,ready=false,saving=false,loading=false,currentUser=null,lastSent='',saveTimer=null,suppressSave=false;
function localKey(){return currentUser&&currentUser.id?LOCAL_BASE+'_'+currentUser.id:LOCAL_BASE;}
function toast(m){if(typeof window.toast==='function')window.toast(m);else console.log('[cloud]',m);}
function loadSDK(){return new Promise(function(ok,bad){if(window.supabase)return ok();var s=document.createElement('script');s.src=SDK_URL;s.onload=ok;s.onerror=function(){bad(new Error('Не удалось загрузить Supabase'));};document.head.appendChild(s);});}
function client(){if(!sb&&window.supabase)sb=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:window.localStorage,storageKey:'kopeyka3-auth'}});return sb;}
function score(s){if(!s||typeof s!=='object')return 0;var n=0;['income','expenses','reserves','debts','reserveOps','obligations','obligationPays','notes','recurring'].forEach(function(k){if(Array.isArray(s[k]))n+=s[k].length;});if(s.shiftsOverride&&typeof s.shiftsOverride==='object')n+=Object.keys(s.shiftsOverride).length;return n;}
function normalize(raw){var base=typeof window.defaultState==='function'?window.defaultState():{version:6,settings:{openingBalance:0,month:'',dayRate:0,nightRate:0},income:[],expenses:[],reserves:[],debts:[],reserveOps:[],obligations:[],obligationPays:[],shiftsOverride:{}};var r=raw&&typeof raw==='object'?raw:{},o=Object.assign({},base,r);o.settings=Object.assign({},base.settings||{},r.settings||{});['income','expenses','reserves','debts','reserveOps','obligations','obligationPays'].forEach(function(k){if(!Array.isArray(o[k]))o[k]=[];});if(!o.shiftsOverride||typeof o.shiftsOverride!=='object')o.shiftsOverride={};return o;}
function stamp(s){var n=normalize(s);if(!n.updatedAt)n.updatedAt=new Date().toISOString();return n;}
function readLocal(){try{var v=localStorage.getItem(localKey());if(v)return stamp(JSON.parse(v));v=localStorage.getItem(LOCAL_BASE);if(v)return stamp(JSON.parse(v));}catch(_){}return null;}
function writeLocal(s){try{localStorage.setItem(localKey(),JSON.stringify(stamp(s)));}catch(_){} }
function timeOf(s){var t=s&&Date.parse(s.updatedAt||'');return isFinite(t)?t:0;}
function choose(local,cloud){if(!local)return{state:cloud,source:'cloud'};if(!cloud)return{state:local,source:'local'};var lt=timeOf(local),ct=timeOf(cloud);if(lt>ct)return{state:local,source:'local'};if(ct>lt)return{state:cloud,source:'cloud'};return{state:cloud,source:'cloud'};}
function applyState(s,label,upload){var n=stamp(s);writeLocal(n);suppressSave=!upload;try{if(typeof window.setAppState==='function')window.setAppState(n);else if(window.STATE){window.STATE=n;if(typeof window.render==='function')window.render();}}finally{suppressSave=false;}lastSent=JSON.stringify(n);if(label)toast(label);}
async function loadFromCloud(){if(!currentUser)return null;var c=client();if(!c)throw new Error('Облако недоступно');var r=await c.from('user_finance_state').select('state,version,updated_at').eq('user_id',currentUser.id).maybeSingle();if(r.error)throw new Error(r.error.message||r.error.code||'Ошибка загрузки облака');if(!r.data)return null;var state=normalize(r.data.state);if(r.data.updated_at&&!state.updatedAt)state.updatedAt=r.data.updated_at;return state;}
async function saveToCloud(force){if(!currentUser||!ready||suppressSave)return false;if(saving&&!force)return false;saving=true;try{var clean=stamp(window.STATE||readLocal()||{});clean.app='kopeyka3';var json=JSON.stringify(clean);if(!force&&json===lastSent)return true;var c=client();if(!c)throw new Error('Облако недоступно');var now=new Date().toISOString();clean.updatedAt=now;json=JSON.stringify(clean);var r=await c.from('user_finance_state').upsert({user_id:currentUser.id,state:clean,version:13,updated_at:now},{onConflict:'user_id'});if(r.error)throw new Error(r.error.message||r.error.code||'Ошибка сохранения в облако');lastSent=json;writeLocal(clean);return true;}catch(e){console.error('[cloud] save',e);toast('Не удалось сохранить в облако: '+(e.message||''));return false;}finally{saving=false;}}
function scheduleSave(){if(suppressSave)return;clearTimeout(saveTimer);saveTimer=setTimeout(function(){saveToCloud(false);},1200);}
function setStatus(on,msg){var b=document.getElementById('btnCloud');if(b){b.classList.toggle('on',!!on);b.title=msg||(on?'Облако':'Локально');}}
function updateAccountUI(){setStatus(!!currentUser,currentUser?(currentUser.email||'Облако'):'Локально');}
function injectAuthCSS(){if(document.getElementById('cloudAuthCSS'))return;var s=document.createElement('style');s.id='cloudAuthCSS';s.textContent='.cloud-auth{position:fixed;inset:0;background:rgba(0,0,0,.6);z-index:120;display:flex;align-items:center;justify-content:center;padding:16px}.cloud-auth-card{width:100%;max-width:360px;background:#181A21;border:1px solid #2A2D38;border-radius:16px;padding:20px}.cloud-auth-card h2{font-size:18px;margin:0 0 6px}.cloud-auth-card .sm{font-size:13px;color:#8B90A0;margin:0 0 12px;line-height:1.4}.cloud-auth-card .field{margin-bottom:10px}.cloud-auth-card input{width:100%;padding:12px 14px;border-radius:12px;background:#1E2129;border:1px solid #2A2D38;color:#F2F3F7;box-sizing:border-box;font-size:15px}.cloud-auth-card .row{display:flex;gap:8px;margin-top:4px}.cloud-auth-card .btn{flex:1;padding:12px;border-radius:12px;font-weight:600;border:1px solid #2A2D38;background:#1E2129;color:#F2F3F7;cursor:pointer;font-size:14px}.cloud-auth-card .btn.bp{background:linear-gradient(135deg,#F0C384,#E5A75E);color:#1A1208;border:none}.cloud-auth-card .btn.full{width:100%;margin-top:8px;display:block}.cloud-auth-card .btn:disabled{opacity:.55;cursor:wait}.cloud-auth-msg{font-size:13px;min-height:18px;margin-bottom:8px;color:#F87171}.cloud-auth-msg.ok{color:#4ADE80}.cloud-user{padding:12px;border-radius:12px;background:#1E2129;border:1px solid #2A2D38;margin-bottom:12px;font-size:14px;word-break:break-all}';document.head.appendChild(s);}
function closeAuth(){var r=document.getElementById('cloudAuth');if(r)r.remove();}
function showAuth(){injectAuthCSS();closeAuth();var root=document.createElement('div');root.id='cloudAuth';root.className='cloud-auth';if(currentUser)root.innerHTML='<div class="cloud-auth-card"><h2>Облако</h2><p class="sm">Аккаунт подключен.</p><div class="cloud-user">'+(currentUser.email||currentUser.id)+'</div><div class="cloud-auth-msg" id="cloudAuthMsg"></div><button type="button" class="btn bp full" id="cloudSyncBtn">Загрузить мои данные</button><button type="button" class="btn full" id="cloudSaveBtn">Сохранить сейчас</button><button type="button" class="btn full" id="cloudLogout">Выйти</button><button type="button" class="btn full" id="cloudAuthClose">Закрыть</button></div>';else root.innerHTML='<div class="cloud-auth-card"><h2>Вход в облако</h2><p class="sm">Данные аккаунта не пересекаются с другими.</p><div class="cloud-auth-msg" id="cloudAuthMsg"></div><div class="field"><input type="email" id="cloudEmailIn" placeholder="Email" autocomplete="username" inputmode="email"></div><div class="field"><input type="password" id="cloudPassIn" placeholder="Пароль" autocomplete="current-password"></div><div class="row"><button type="button" class="btn" id="cloudLoginBtn">Войти</button><button type="button" class="btn bp" id="cloudSignBtn">Регистрация</button></div><button type="button" class="btn full" id="cloudAuthClose">Закрыть</button></div>';document.body.appendChild(root);root.addEventListener('click',function(e){if(e.target===root)closeAuth();});var close=document.getElementById('cloudAuthClose');if(close)close.onclick=closeAuth;function msg(t,ok){var m=document.getElementById('cloudAuthMsg');if(m){m.textContent=t||'';m.className='cloud-auth-msg'+(ok?' ok':'');}}async function auth(signup){var e=(document.getElementById('cloudEmailIn')||{}).value||'',p=(document.getElementById('cloudPassIn')||{}).value||'';e=e.trim();if(!e||!p)return msg('Введи email и пароль');if(p.length<6)return msg('Пароль минимум 6 символов');var a=document.getElementById('cloudLoginBtn'),b=document.getElementById('cloudSignBtn');if(a)a.disabled=true;if(b)b.disabled=true;msg(signup?'Регистрация…':'Вход…');try{await loadSDK();var c=client(),r=signup?await c.auth.signUp({email:e,password:p}):await c.auth.signInWithPassword({email:e,password:p});if(r.error)throw r.error;if(signup&&!r.data.session){msg('Подтверди email из письма, потом войди',true);return;}await onSession(r.data.session);closeAuth();}catch(x){var m=x&&(x.message||x.error_description||String(x));if(/invalid login|invalid credentials/i.test(m))m='Неверный email или пароль';else if(/email not confirmed/i.test(m))m='Подтверди email по ссылке из письма';else if(/rate limit|too many/i.test(m))m='Слишком много попыток';msg(m);}finally{if(a)a.disabled=false;if(b)b.disabled=false;}}
var lb=document.getElementById('cloudLoginBtn'),sb2=document.getElementById('cloudSignBtn');if(lb)lb.onclick=function(){auth(false);};if(sb2)sb2.onclick=function(){auth(true);};var pass=document.getElementById('cloudPassIn');if(pass)pass.addEventListener('keydown',function(e){if(e.key==='Enter')auth(false);});var sync=document.getElementById('cloudSyncBtn');if(sync)sync.onclick=async function(){sync.disabled=true;msg('Загрузка…');try{var cloud=await loadFromCloud(),local=readLocal();if(!cloud&&!local){msg('В облаке и на устройстве нет данных');return;}var pick=choose(local,cloud);applyState(pick.state,pick.source==='cloud'?'Данные из облака загружены':'Локальные данные сохранены',false);if(pick.source==='local')await saveToCloud(true);msg('Синхронизация завершена',true);}catch(e){msg(e.message||'Ошибка загрузки');}finally{sync.disabled=false;}};var save=document.getElementById('cloudSaveBtn');if(save)save.onclick=async function(){save.disabled=true;msg('Сохранение…');var ok=await saveToCloud(true);msg(ok?'Сохранено в облако':'Ошибка сохранения',ok);save.disabled=false;};var lo=document.getElementById('cloudLogout');if(lo)lo.onclick=async function(){lo.disabled=true;try{await client().auth.signOut({scope:'local'});}catch(_){}currentUser=null;ready=false;lastSent='';updateAccountUI();closeAuth();toast('Вышли');};}
async function onSession(session){if(!session||!session.user){currentUser=null;ready=false;updateAccountUI();return;}if(loading)return;loading=true;try{currentUser=session.user;ready=true;updateAccountUI();var local=readLocal(),cloud=await loadFromCloud(),pick=choose(local,cloud);if(pick.state){applyState(pick.state,pick.source==='cloud'?'Данные аккаунта загружены':'Локальные данные → облако',false);if(pick.source==='local')await saveToCloud(true);}else toast('Вход выполнен, данных пока нет');}catch(e){console.error('[cloud] session',e);toast('Ошибка облака: '+(e.message||''));}finally{loading=false;}}
async function bootCloud(){try{await loadSDK();var c=client();if(!c)throw new Error('Клиент не готов');var res=await c.auth.getSession();await onSession(res.data&&res.data.session);c.auth.onAuthStateChange(function(ev,session){if(ev==='SIGNED_OUT'){currentUser=null;ready=false;updateAccountUI();return;}if(ev==='SIGNED_IN'||ev==='TOKEN_REFRESHED'||ev==='INITIAL_SESSION')setTimeout(function(){onSession(session);},0);});}catch(e){console.error('[cloud] boot',e);setStatus(false,'Офлайн');}var btn=document.getElementById('btnCloud');if(btn)btn.onclick=showAuth;}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootCloud);else bootCloud();
window.kopeykaCloud={save:function(){return saveToCloud(true);},user:function(){return currentUser;},scheduleSave:scheduleSave,load:function(){return loadFromCloud();},showAuth:showAuth};
})();
