(function(){
'use strict';
var CATS=['Продукты','Алкоголь','Сигареты','Хозтовары','Бытовая химия','Кафе','Связь','Проезд','Жильё','Здоровье','Красота','Одежда','Развлечения','Подписки','Техника','Дети','Животные','Обязательные','Долг','Прочее'];
var ANCHOR='2026-08-17',CYCLE=['day','day','night','night','off','off'],MONTHS=['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'];
function n(v){var x=Number(v);return isFinite(x)&&x===x?Math.round(x):0;}
function state(){return window.STATE&&typeof window.STATE==='object'?window.STATE:{};}
function today(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function monthOf(d){return String(d||'').slice(0,7);}
function days(a,b){var pa=String(a).split('-').map(Number),pb=String(b).split('-').map(Number);return Math.round((new Date(pb[0],pb[1]-1,pb[2])-new Date(pa[0],pa[1]-1,pa[2]))/864e5);}
function next(m){var p=String(m).split('-').map(Number),y=p[0],x=p[1]+1;if(x>12){x=1;y++;}return y+'-'+String(x).padStart(2,'0');}
function prev(m){var p=String(m).split('-').map(Number),y=p[0],x=p[1]-1;if(x<1){x=12;y--;}return y+'-'+String(x).padStart(2,'0');}
function monthOps(m){var s=state(),inc=0,exp=0,dep=0,wd=0;(s.income||[]).forEach(function(x){if(monthOf(x.date)===m)inc+=n(x.amount);});(s.expenses||[]).forEach(function(x){if(monthOf(x.date)===m)exp+=n(x.amount);});(s.reserveOps||[]).forEach(function(x){if(monthOf(x.date)!==m)return;var a=n(x.amount);if(x.type==='deposit')dep+=a;else if(x.type==='withdraw')wd+=a;});return{income:inc,expenses:exp,deposits:dep,withdrawals:wd,delta:inc-exp-dep+wd};}
function selectedMonth(){if(window.__kopeykaViewMonth)return window.__kopeykaViewMonth;var el=document.querySelector('.month-title');var txt=el&&el.textContent||'';var i=MONTHS.indexOf(String(txt).trim().split(/\s+/)[0]);var y=String(txt).trim().split(/\s+/)[1];if(i>=0&&/^\d{4}$/.test(y))return y+'-'+String(i+1).padStart(2,'0');var s=state();return s.settings&&s.settings.month||today().slice(0,7);}
function opening(m){var s=state(),anchor=s.settings&&s.settings.month||today().slice(0,7),open=n(s.settings&&s.settings.openingBalance),guard=0;if(m===anchor)return open;if(m>anchor){for(var x=anchor;x!==m&&guard++<240;x=next(x))open+=monthOps(x).delta;return open;}for(var y=anchor;y!==m&&guard++<240;){y=prev(y);open-=monthOps(y).delta;}return open;}
function calc(m){var s=state(),o=monthOps(m),cash=opening(m)+o.delta,debt=0,res=0,obDue=0,obPaid=0;(s.debts||[]).forEach(function(d){debt+=Math.max(0,n(d.total)-n(d.paid));});(s.reserves||[]).forEach(function(r){res+=n(r.saved);});(s.obligations||[]).forEach(function(ob){if(ob.active===false)return;var p=0;(s.obligationPays||[]).forEach(function(x){if(x.obligId===ob.id&&x.month===m)p+=n(x.amount);});obPaid+=p;obDue+=Math.max(0,n(ob.amount)-p);});var available=cash-debt-obDue,p=m.split('-').map(Number),last=new Date(p[0],p[1],0).getDate(),cur=today().slice(0,7),left=m===cur?Math.max(1,last-Number(today().slice(8))+1):last,daily=available>0?Math.floor(available/left):0,by={};(s.expenses||[]).forEach(function(e){if(monthOf(e.date)!==m)return;var c=e.category||'Прочее';if(c==='Долг'&&e.note)c=e.note;by[c]=(by[c]||0)+n(e.amount);});var cats=Object.keys(by).map(function(k){return{name:k,amount:by[k]};}).sort(function(a,b){return b.amount-a.amount;});return{month:m,openingBalance:opening(m),cash:cash,available:available,dailyBudget:daily,daysLeft:left,income:o.income,expenses:o.expenses,reserveDeposits:o.deposits,reserveWithdrawals:o.withdrawals,reservesTotal:res,debtRemaining:debt,obligationsRemaining:obDue,obligationsPaid:obPaid,expenseByCategory:cats};}
function shifts(m){var s=state(),p=m.split('-').map(Number),dim=new Date(p[0],p[1],0).getDate(),out={day:0,night:0,off:0};for(var d=1;d<=dim;d++){var ds=m+'-'+String(d).padStart(2,'0'),v=s.shiftsOverride&&s.shiftsOverride[ds];if(v!=='day'&&v!=='night'&&v!=='off')v=CYCLE[((days(ANCHOR,ds)%6)+6)%6];out[v]++;}return out;}
function clone(x){try{return JSON.parse(JSON.stringify(x));}catch(e){return x;}}
function snapshot(){var s=state(),m=selectedMonth(),all={settings:clone(s.settings||{}),selectedMonth:m,calculations:calc(m),shifts:shifts(m),income:clone(s.income||[]),expenses:clone(s.expenses||[]),reserves:clone(s.reserves||[]),reserveOps:clone(s.reserveOps||[]),debts:clone(s.debts||[]),obligations:clone(s.obligations||[]),obligationPays:clone(s.obligationPays||[]),shiftsOverride:clone(s.shiftsOverride||{})};return all;}
function context(){var s=snapshot();return JSON.stringify(s);}
window.kopeykaEngine={categories:CATS,getSelectedMonth:selectedMonth,month:calc,shifts:shifts,snapshot:snapshot,context:context};
})();
