(function(){
'use strict';
var SR=window.SpeechRecognition||window.webkitSpeechRecognition;
var CATS=['Продукты','Алкоголь','Сигареты','Хозтовары','Бытовая химия','Кафе','Связь','Проезд','Жильё','Здоровье','Красота','Одежда','Развлечения','Подписки','Техника','Дети','Животные','Обязательные','Долг','Прочее'];
var RES_PRESETS=['Подушка безопасности','Права','Отпуск','Ремонт','Налог','Больница'];
var recognition=null,listening=false,pendingStep=null;
var TTS_KEY='kopeyka_tts_on';
function ttsOn(){try{return localStorage.getItem(TTS_KEY)!=='0';}catch(e){return true;}}
function setTtsOn(v){try{localStorage.setItem(TTS_KEY,v?'1':'0');}catch(e){}}
function speak(text){if(!ttsOn()||!window.speechSynthesis||!text)return;try{window.speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(String(text));u.lang='ru-RU';u.rate=1.05;u.pitch=1;var voices=window.speechSynthesis.getVoices()||[];var ru=voices.find(function(v){return (v.lang||'').toLowerCase().indexOf('ru')===0;});if(ru)u.voice=ru;window.speechSynthesis.speak(u);}catch(e){}}
function say(status,detail){setUI(status,detail||'');speak(((status||'')+(detail?' . '+detail:'')).replace(/[•·]/g,' ').replace(/\s+/g,' ').trim());}
function norm(s){return String(s||'').toLowerCase().replace(/ё/g,'е').replace(/[^a-zа-я0-9.,-]+/gi,' ').replace(/\s+/g,' ').trim();}
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function cloneState(){return JSON.parse(JSON.stringify(window.STATE));}
function applyState(s){if(typeof window.setAppState!=='function')throw new Error('Приложение ещё не готово');window.setAppState(s);}
function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7);}
function capitalize(s){s=String(s||'').trim();if(!s)return'';return s.charAt(0).toUpperCase()+s.slice(1);}
function fmt(n){return Math.round(+n||0).toLocaleString('ru-RU');}
function hasAny(s,words){for(var i=0;i<words.length;i++){if(s.indexOf(words[i])!==-1)return true;}return false;}
function getLearned(){var st=window.STATE||{};return (st.voiceMap&&typeof st.voiceMap==='object')?st.voiceMap:{};}
function learnCategory(item,cat){if(!item||!cat)return;var key=norm(item);if(!key||key.length<2)return;var s=cloneState();if(!s.voiceMap||typeof s.voiceMap!=='object')s.voiceMap={};s.voiceMap[key]=cat;var parts=key.split(' ').filter(Boolean);if(parts.length===1)s.voiceMap[parts[0]]=cat;applyState(s);}
var ONES={ноль:0,один:1,одна:1,одну:1,два:2,две:2,три:3,четыре:4,пять:5,шесть:6,семь:7,восемь:8,девять:9,десять:10,одиннадцать:11,двенадцать:12,тринадцать:13,четырнадцать:14,пятнадцать:15,шестнадцать:16,семнадцать:17,восемнадцать:18,девятнадцать:19};
var TENS={двадцать:20,тридцать:30,сорок:40,пятьдесят:50,шестьдесят:60,семьдесят:70,восемьдесят:80,девяносто:90};
var HUND={сто:100,двести:200,триста:300,четыреста:400,пятьсот:500,шестьсот:600,семьсот:700,восемьсот:800,девятьсот:900};
function cleanForAmount(s){s=String(s||'').toLowerCase().replace(/ё/g,'е');s=s.replace(/([а-яa-z])[.,]+([а-яa-z])/gi,'$1 $2');s=s.replace(/([а-яa-z])[.,]+/gi,'$1 ');s=s.replace(/[.,]+([а-яa-z])/gi,' $1');s=s.replace(/(\d)[.,\s](\d{3})(?!\d)/g,'$1$2');s=s.replace(/[^a-zа-я0-9\s-]+/gi,' ');return s.replace(/\s+/g,' ').trim();}
function wordsNumber(s){var a=cleanForAmount(s).replace(/руб(лей|ля|ль)?/g,'').split(' ').filter(Boolean),total=0,cur=0,seen=false;for(var i=0;i<a.length;i++){var w=a[i].replace(/^[.,]+|[.,]+$/g,'');if(!w)continue;if(/^\d+$/.test(w)){cur+=Number(w);seen=true;continue;}if(ONES[w]!==undefined){cur+=ONES[w];seen=true;continue;}if(TENS[w]!==undefined){cur+=TENS[w];seen=true;continue;}if(HUND[w]!==undefined){cur+=HUND[w];seen=true;continue;}if(w==='тысяча'||w==='тысячи'||w==='тысяч'||w==='тыс'||w==='тыща'||w==='тыщи'){total+=(cur||1)*1000;cur=0;seen=true;continue;}if(w==='миллион'||w==='миллиона'||w==='миллионов'){total+=(cur||1)*1000000;cur=0;seen=true;}}return seen?total+cur:0;}
function extractAmount(text){var s=cleanForAmount(text);if(/тысяч|тыс\b|тыща|тыщи|миллион/.test(s)){var mix=s.match(/(\d+)\s*(тыс(?:яч(?:а|и)?)?|тыща|тыщи|миллион(?:а|ов)?)/);if(mix){var base=Number(mix[1]);if(isFinite(base)&&base>0){if(String(mix[2]).indexOf('миллион')===0)return Math.round(base*1000000);return Math.round(base*1000);}}var w=wordsNumber(s);if(w>0)return w;}var onlyWords=wordsNumber(s);if(onlyWords>0&&!/\d/.test(s))return onlyWords;var m=s.match(/(?:^|\s)(\d{1,9})(?:\s*(?:руб(?:лей|ля|ль)?|р))?(?=\s|$)/);if(m){var n=Number(m[1]);if(isFinite(n)&&n>0&&n<1e9)return Math.round(n);}return onlyWords||0;}
var PRODUCT_RULES=window.KOPEYKA_PRODUCTS||[];
function categoryFromText(text){var s=norm(text),learned=getLearned(),keys=Object.keys(learned),bestL='',scoreL=0;for(var i=0;i<keys.length;i++){var k=keys[i];if(k&&s.indexOf(k)!==-1&&k.length>scoreL){scoreL=k.length;bestL=learned[k];}}if(bestL)return bestL;var best='',score=0;PRODUCT_RULES.forEach(function(rule){var local=0;rule[1].forEach(function(k){if(s.indexOf(k)!==-1)local+=k.length;});if(local>score){score=local;best=rule[0];}});return best;}
function typeFromText(text){var s=norm(text);if(hasAny(s,['доход','получил','получила','получить','получено','зарплат','заработал','заработала','начисл','пришли деньги','пришел доход','выдали','аванс','преми','получка','подработк','фриланс','гонорар']))return 'income';if(hasAny(s,['расход','потрат','купил','купила','купить','покупал','покупала','оплатил','оплатила','заплатил','заплатила','потрач','ушло','покупк','приобрел','приобрела','приобрести']))return 'expense';if(categoryFromText(s))return 'expense';return '';}
function isQuery(s){return hasAny(s,['сколько','какой баланс','какой остаток','что с кассой','расскажи','статус','как дела','сколько осталось','до цели']);}
function isReserveCmd(s){return hasAny(s,['резерв','отлож','подушк','копить','накоплен','цель накоп'])&&!isQuery(s);}
function isDebtCmd(s){return hasAny(s,['долг','должен','должна','занял','заняла'])&&!isQuery(s);}
function isObligCmd(s){return hasAny(s,['обязательн','алименты','ежемесячн'])&&!isQuery(s);}
function isWithdraw(s){return hasAny(s,['сними','снять','вытащи','взял из','из резерва']);}
function isPayDebt(s){return hasAny(s,['верни','вернуть','погаси','погасить','платеж','платежа','оплати долг']);}
function isDeleteLast(s){return hasAny(s,['удали последн','удалить последн','отмени последн','отменить последн','убери последн','удали расход','удали доход']);}
function stripNoise(text){var s=norm(text);s=s.replace(/\d+(?:[.,]\d+)?/g,' ');'ноль один одна одну два две три четыре пять шесть семь восемь девять десять одиннадцать двенадцать тринадцать четырнадцать пятнадцать шестнадцать семнадцать восемнадцать девятнадцать двадцать тридцать сорок пятьдесят шестьдесят семьдесят восемьдесят девяносто сто двести триста четыреста пятьсот шестьсот семьсот восемьсот девятьсот тысяча тысячи тысяч тыс миллион миллиона миллионов'.split(' ').forEach(function(w){s=s.split(w).join(' ');});s=s.replace(/\b(руб(?:лей|ля|ль)?|р|₽)\b/g,' ');'добавь добавить запиши записать внеси внести создай сделай учти покажи мне пожалуйста расход доход потратил потратила потратить купил купила купить покупал покупала оплатил оплатила оплатить заплатил заплатила заплатить получил получила получить заработал заработала заработать зарплата зарплатой приобрел приобрела приобрести взял взяла подработка подработкой аванс премия резерв резерва отложить отложи пополнить пополни накопить цель сумма сумму долг должен должна обязательный обязательные алименты сколько удали удалить'.split(' ').forEach(function(w){s=s.split(w).join(' ');});s=s.replace(/\b(на|за|в|во|из|от|с|со|мне|это|стоил|стоит|рублей|рубля|сегодня|вчера)\b/g,' ');return s.replace(/\s+/g,' ').trim();}
function itemFromText(text){var item=stripNoise(text);return item?capitalize(item):'';}
function matchReserveName(text){var s=norm(text);for(var i=0;i<RES_PRESETS.length;i++){var p=norm(RES_PRESETS[i]);if(s.indexOf(p)!==-1)return RES_PRESETS[i];var short=p.split(' ')[0];if(short.length>3&&s.indexOf(short)!==-1)return RES_PRESETS[i];}var cleaned=stripNoise(text).trim();return cleaned?capitalize(cleaned):'';}
function addExpense(amount,category,note){var s=cloneState();s.expenses=Array.isArray(s.expenses)?s.expenses:[];s.expenses.push({id:id(),amount:amount,category:category||'Прочее',note:note||'',date:new Date().toISOString().slice(0,10)});applyState(s);if(note)learnCategory(note,category);}
function addIncome(amount,note){var s=cloneState();s.income=Array.isArray(s.income)?s.income:[];s.income.push({id:id(),amount:amount,note:note||'Доход',date:new Date().toISOString().slice(0,10)});applyState(s);}
function findReserve(s,name){var q=norm(name);return (s.reserves||[]).find(function(r){return norm(r.name)===q||norm(r.category)===q||q.indexOf(norm(r.name))!==-1||norm(r.name).indexOf(q)!==-1;});}
function createOrTopupReserve(name,target,deposit,withdraw){var s=cloneState();s.reserves=Array.isArray(s.reserves)?s.reserves:[];s.reserveOps=Array.isArray(s.reserveOps)?s.reserveOps:[];var r=findReserve(s,name||'');if(!r){r={id:id(),name:name||'Свой вариант',category:name||'Свой вариант',target:Number(target)||0,saved:0};s.reserves.push(r);}else if(target>0)r.target=Number(target);var amount=Number(deposit||0);if(withdraw){if(amount>Number(r.saved||0))throw new Error('В резерве только '+fmt(r.saved)+' ₽');r.saved=Number(r.saved||0)-amount;if(amount>0)s.reserveOps.push({id:id(),reserveId:r.id,type:'withdraw',amount:amount,date:new Date().toISOString().slice(0,10)});}else if(amount>0){r.saved=Number(r.saved||0)+amount;s.reserveOps.push({id:id(),reserveId:r.id,type:'deposit',amount:amount,date:new Date().toISOString().slice(0,10)});}applyState(s);return r.name;}
function addDebt(amount,name){var s=cloneState();s.debts=Array.isArray(s.debts)?s.debts:[];s.debts.push({id:id(),name:name||'Долг',total:amount,paid:0});applyState(s);}
function payDebt(amount,name){var s=cloneState();s.debts=Array.isArray(s.debts)?s.debts:[];var q=norm(name||''),d=s.debts.find(function(x){return q&&norm(x.name).indexOf(q)!==-1;})||s.debts.find(function(x){return Number(x.total||0)>Number(x.paid||0);});if(!d)throw new Error('Подходящий долг не найден');d.paid=Number(d.paid||0)+amount;s.expenses=Array.isArray(s.expenses)?s.expenses:[];s.expenses.push({id:id(),amount:amount,category:'Долг',note:d.name,date:new Date().toISOString().slice(0,10)});applyState(s);return d.name;}
function addObligation(amount,name,day){var s=cloneState();s.obligations=Array.isArray(s.obligations)?s.obligations:[];s.obligations.push({id:id(),name:name||'Платёж',amount:amount,day:day||25,active:true});applyState(s);}
function deleteLastOp(){var s=cloneState();var lastEx=(s.expenses&&s.expenses.length)?s.expenses[s.expenses.length-1]:null;var lastIn=(s.income&&s.income.length)?s.income[s.income.length-1]:null;if(!lastEx&&!lastIn)throw new Error('Нечего удалять');var pickEx=true;if(lastEx&&lastIn)pickEx=String(lastEx.id)>=String(lastIn.id);else if(!lastEx)pickEx=false;if(pickEx){s.expenses=s.expenses.filter(function(x){return x.id!==lastEx.id;});applyState(s);return 'Удалила расход «'+(lastEx.note||lastEx.category||'')+'» на '+fmt(lastEx.amount)+' ₽';}s.income=s.income.filter(function(x){return x.id!==lastIn.id;});applyState(s);return 'Удалила доход «'+(lastIn.note||'Доход')+'» на '+fmt(lastIn.amount)+' ₽';}
function answerQuery(text){var s=norm(text),st=window.STATE||{},month=(st.settings&&st.settings.month)||new Date().toISOString().slice(0,7);function inMonth(d){return String(d||'').slice(0,7)===month;}var open=Number(st.settings&&st.settings.openingBalance||0),inc=0,exp=0,dep=0,wd=0;(st.income||[]).forEach(function(i){if(inMonth(i.date))inc+=Number(i.amount||0);});(st.expenses||[]).forEach(function(e){if(inMonth(e.date))exp+=Number(e.amount||0);});(st.reserveOps||[]).forEach(function(o){if(!inMonth(o.date))return;var a=Number(o.amount||0);if(o.type==='deposit')dep+=a;else wd+=a;});var cash=open+inc-exp-dep+wd,debt=0;(st.debts||[]).forEach(function(d){debt+=Math.max(0,Number(d.total||0)-Number(d.paid||0));});if(hasAny(s,['подушк','резерв','накоп','цель','отпуск','больниц','права','ремонт','налог'])){var name=matchReserveName(s),list=st.reserves||[],r=name?findReserve(st,name):null;if(!r&&list.length===1)r=list[0];if(!r&&hasAny(s,['подушк']))r=list.find(function(x){return norm(x.name).indexOf('подушк')!==-1;})||null;if(r){var saved=Number(r.saved||0),target=Number(r.target||0),left=Math.max(0,target-saved),pct=target>0?Math.round(saved/target*100):0;if(hasAny(s,['до цели','осталось','сколько ещё','не хватает']))return target?('До цели «'+r.name+'» осталось '+fmt(left)+' ₽. Сейчас '+fmt(saved)+' из '+fmt(target)+'.'):('У «'+r.name+'» цели нет. Накоплено '+fmt(saved)+' ₽.');return 'В резерве «'+r.name+'»: '+fmt(saved)+' ₽'+(target?' из '+fmt(target)+' ('+pct+'%)':'')+'.';}if(list.length){var total=list.reduce(function(a,x){return a+Number(x.saved||0);},0);return 'Во всех резервах '+fmt(total)+' ₽. Резервов: '+list.length+'.';}return 'Резервов пока нет.';}if(hasAny(s,['долг']))return debt?('Остаток по долгам '+fmt(debt)+' ₽.'):'Долгов нет — красавчик.';if(hasAny(s,['касс','баланс','остаток','доступн','на день','сколько денег']))return 'Касса '+fmt(cash)+' ₽. Доходы за месяц +'+fmt(inc)+', расходы −'+fmt(exp)+'.';if(hasAny(s,['расход']))return 'Расходы за месяц '+fmt(exp)+' ₽.';if(hasAny(s,['доход']))return 'Доходы за месяц '+fmt(inc)+' ₽.';return 'Касса '+fmt(cash)+' ₽, расходы −'+fmt(exp)+', в резервах '+fmt((st.reserves||[]).reduce(function(a,x){return a+Number(x.saved||0);},0))+' ₽.';}
function setUI(status,text){var a=document.getElementById('voiceStatus'),b=document.getElementById('voiceText'),o=document.getElementById('voiceOrb');if(a)a.textContent=status;if(b)b.textContent=text||'';if(o)o.classList.toggle('listening',listening);}
function closeUI(){pendingStep=null;if(recognition){try{recognition.onresult=null;recognition.stop();}catch(e){}recognition=null;}listening=false;var m=document.getElementById('voiceModal');if(m)m.remove();}
function startListening(){if(!SR){say('Голосовой ввод недоступен','Открой Копейку в Chrome на Android.');return;}if(recognition){try{recognition.stop();}catch(e){}}recognition=new SR();recognition.lang='ru-RU';recognition.interimResults=true;recognition.continuous=false;recognition.maxAlternatives=5;listening=true;setUI('Слушаю…','');recognition.onresult=function(e){var text='';for(var i=e.resultIndex;i<e.results.length;i++)text+=e.results[i][0].transcript+' ';text=text.trim();setUI('Слышу',text);if(e.results[e.results.length-1].isFinal){if(pendingStep&&typeof pendingStep.onSpeech==='function')pendingStep.onSpeech(text);else processCommand(text);}};recognition.onerror=function(e){listening=false;say(e.error==='not-allowed'?'Нет доступа к микрофону':'Не удалось распознать','Нажми микрофон ещё раз.');};recognition.onend=function(){listening=false;var o=document.getElementById('voiceOrb');if(o)o.classList.remove('listening');};try{recognition.start();}catch(e){}}
function btnStyle(primary,danger){var base='flex:1;min-width:100px;min-height:52px;padding:14px 12px;border-radius:14px;font-weight:700;font-size:16px;display:flex;align-items:center;justify-content:center;cursor:pointer;';if(primary)return base+'background:linear-gradient(135deg,#F0C384,#E5A75E);color:#1A1208;border:none;';if(danger)return base+'background:rgba(248,113,113,.18);color:#F87171;border:1px solid rgba(248,113,113,.4);';return base+'background:#1C1F28;color:#F2F3F7;border:1px solid rgba(255,255,255,.14);'}
function actionsBar(html){return '<div id="voiceActions" style="display:flex!important;gap:8px;margin-top:16px;width:100%;flex-wrap:wrap;z-index:10">'+html+'</div>';}
function confirmBox(title,details,onYes){var card=document.querySelector('#voiceModal .voice-card');if(!card)return;pendingStep=null;card.innerHTML='<div style="display:flex;justify-content:space-between;align-items:flex-start;text-align:left"><div><div style="font-size:11px;color:#9AA0B0;text-transform:uppercase;letter-spacing:.06em">Проверь операцию</div><div style="font-size:19px;font-weight:700;margin-top:3px">'+esc(title)+'</div></div><button type="button" id="voiceClose" style="width:36px;height:36px;border-radius:10px;background:#1C1F28;font-size:24px;border:none;color:#F2F3F7">×</button></div><div style="padding:18px 8px;font-size:16px;line-height:1.7">'+details+'</div>'+actionsBar('<button type="button" id="voiceYes" style="'+btnStyle(true)+'">Подтвердить</button><button type="button" id="voiceNo" style="'+btnStyle()+'">Ещё раз</button><button type="button" id="voiceCancel" style="'+btnStyle(false,true)+'">Отменить</button>');document.getElementById('voiceClose').onclick=closeUI;document.getElementById('voiceCancel').onclick=closeUI;document.getElementById('voiceNo').onclick=function(){pendingStep=null;renderVoice();startListening();};document.getElementById('voiceYes').onclick=function(){try{onYes();say('Готово','Операция добавлена');setTimeout(closeUI,900);}catch(e){say('Не добавлено',e.message||'Ошибка');}};}
function askStep(title,hint,onSpeech){var card=document.querySelector('#voiceModal .voice-card');if(!card)return;pendingStep={onSpeech:onSpeech};card.innerHTML='<div style="display:flex;justify-content:space-between;align-items:flex-start;text-align:left"><div><div style="font-size:11px;color:#9AA0B0;text-transform:uppercase;letter-spacing:.06em">Голосовой ввод</div><div style="font-size:19px;font-weight:700;margin-top:3px">'+esc(title)+'</div></div><button type="button" id="voiceClose" style="width:36px;height:36px;border-radius:10px;background:#1C1F28;font-size:24px;border:none;color:#F2F3F7">×</button></div><button type="button" id="voiceOrb" style="width:82px;height:82px;border-radius:50%;margin:18px auto 12px;background:linear-gradient(135deg,#F0C384,#E5A75E);display:flex;align-items:center;justify-content:center;font-size:36px;border:0">🎙️</button><div id="voiceStatus" style="font-size:13px;color:#9AA0B0;min-height:20px">Слушаю…</div><div id="voiceText" style="min-height:34px;margin:8px 0;font-size:16px"></div><div style="font-size:12px;color:#9AA0B0;line-height:1.5;padding:8px">'+esc(hint)+'</div>'+actionsBar('<button type="button" id="voiceAgain" style="'+btnStyle(true)+'">Говорить</button><button type="button" id="voiceCancel" style="'+btnStyle(false,true)+'">Отменить</button>');document.getElementById('voiceClose').onclick=closeUI;document.getElementById('voiceCancel').onclick=closeUI;document.getElementById('voiceAgain').onclick=startListening;document.getElementById('voiceOrb').onclick=startListening;speak(title);startListening();}
function categoryPicker(amount,note){var card=document.querySelector('#voiceModal .voice-card');if(!card)return;pendingStep=null;card.innerHTML='<div style="display:flex;justify-content:space-between;align-items:flex-start;text-align:left"><div><div style="font-size:11px;color:#9AA0B0;text-transform:uppercase;letter-spacing:.06em">Расход</div><div style="font-size:19px;font-weight:700;margin-top:3px">Выбери категорию</div></div><button type="button" id="voiceClose" style="width:36px;height:36px;border-radius:10px;background:#1C1F28;font-size:24px;border:none;color:#F2F3F7">×</button></div><div style="padding:14px 8px"><b style="font-size:26px">−'+fmt(amount)+' ₽</b><br>'+esc(note||'Без названия')+'</div><div style="display:grid;grid-template-columns:repeat(2,1fr);gap:7px;margin:8px 0;max-height:40vh;overflow:auto">'+CATS.map(function(c){return '<button type="button" data-cat="'+esc(c)+'" style="padding:12px 8px;border-radius:11px;background:#1C1F28;border:1px solid rgba(255,255,255,.12);font-weight:600;font-size:13px;color:#F2F3F7">'+esc(c)+'</button>';}).join('')+'</div>'+actionsBar('<button type="button" id="voiceCancelCat" style="'+btnStyle(false,true)+'">Отменить</button>');document.getElementById('voiceClose').onclick=closeUI;document.getElementById('voiceCancelCat').onclick=closeUI;card.querySelectorAll('[data-cat]').forEach(function(b){b.onclick=function(){var cat=b.getAttribute('data-cat');learnCategory(note,cat);confirmBox('Расход −'+fmt(amount)+' ₽','Название: <b>'+esc(note||'Расход')+'</b><br>Категория: <b>'+esc(cat)+'</b><br><span style="color:#9AA0B0;font-size:13px">Запомню для следующих раз</span>',function(){addExpense(amount,cat,note);});};});}
function startReserveFlow(nameHint,amountHint,isWd){var name=nameHint||'';function afterName(nm){name=nm;if(amountHint>0){confirmBox((isWd?'Снять из резерва ':'Пополнить резерв ')+fmt(amountHint)+' ₽','Резерв: <b>'+esc(name)+'</b>',function(){createOrTopupReserve(name,0,amountHint,isWd);});return;}askStep('Сколько накопить?','Скажи цель: «пятьдесят тысяч», «сто тысяч» или «ноль»',function(speech){var target=extractAmount(speech)||0;askStep('Сколько положить сейчас?','Скажи сумму или «ноль»',function(speech2){var dep=extractAmount(speech2)||0;confirmBox('Резерв «'+name+'»','Цель: <b>'+(target?fmt(target)+' ₽':'без цели')+'</b><br>Сейчас: <b>'+fmt(dep)+' ₽</b>',function(){createOrTopupReserve(name,target,dep,false);});});});}if(name)afterName(name);else askStep('Какой резерв?','Скажи: «подушка безопасности», «отпуск»…',function(speech){afterName(matchReserveName(speech)||capitalize(stripNoise(speech))||'Свой вариант');});}
function processCommand(text){var s=norm(text),amount=extractAmount(text),type=typeFromText(s),cat=categoryFromText(s),item=itemFromText(s);
if(isQuery(s)||(hasAny(s,['сколько','баланс','касса','статус'])&&!amount&&type!=='income')){var ans=answerQuery(text);say('Ответ',ans);var card=document.querySelector('#voiceModal .voice-card');if(card){card.innerHTML='<div style="display:flex;justify-content:space-between;align-items:flex-start;text-align:left"><div><div style="font-size:11px;color:#9AA0B0;text-transform:uppercase;letter-spacing:.06em">Ответ</div><div style="font-size:19px;font-weight:700;margin-top:3px">Копейка</div></div><button type="button" id="voiceClose" style="width:36px;height:36px;border-radius:10px;background:#1C1F28;font-size:24px;border:none;color:#F2F3F7">×</button></div><div style="padding:20px 8px;font-size:17px;line-height:1.6">'+esc(ans)+'</div>'+actionsBar('<button type="button" id="voiceAgain" style="'+btnStyle(true)+'">Ещё вопрос</button><button type="button" id="voiceCancel" style="'+btnStyle(false,true)+'">Закрыть</button>');document.getElementById('voiceClose').onclick=closeUI;document.getElementById('voiceCancel').onclick=closeUI;document.getElementById('voiceAgain').onclick=function(){renderVoice();startListening();}}return;}
if(isDeleteLast(s)){try{var msg=deleteLastOp();say('Готово',msg);setTimeout(closeUI,1200);}catch(e){say('Не удалось',e.message||'Ошибка');}return;}
if(isReserveCmd(s)){var name=matchReserveName(s);if(!name){var raw=stripNoise(s).trim();name=raw?capitalize(raw):'';}startReserveFlow(name,amount,isWithdraw(s));return;}
if(type==='income'){if(!amount){say('Не нашла сумму','Скажи: зарплата 4800');return;}if(!item||item==='Расход')item='Доход';confirmBox('Доход +'+fmt(amount)+' ₽','Название: <b>'+esc(item)+'</b>',function(){addIncome(amount,item);});return;}
if(isDebtCmd(s)){if(!amount){say('Не нашла сумму','Скажи сумму долга');return;}var dn=capitalize(stripNoise(s).trim()||'Долг');confirmBox((isPayDebt(s)?'Платёж по долгу ':'Новый долг ')+fmt(amount)+' ₽','Имя: <b>'+esc(dn)+'</b>',function(){return isPayDebt(s)?payDebt(amount,dn):addDebt(amount,dn);});return;}
if(isObligCmd(s)){if(!amount){say('Не нашла сумму','Скажи сумму');return;}var on=capitalize(stripNoise(s).trim()||'Платёж');confirmBox('Обязательный платёж '+fmt(amount)+' ₽','Название: <b>'+esc(on)+'</b>',function(){addObligation(amount,on,25);});return;}
if(!amount){say('Не нашла сумму','Скажи: сигареты 100, или «сколько в подушке»');return;}if(!item)item='Расход';if(!cat){categoryPicker(amount,item);return;}confirmBox('Расход −'+fmt(amount)+' ₽','Название: <b>'+esc(item)+'</b><br>Категория: <b>'+esc(cat)+'</b>',function(){addExpense(amount,cat,item);});}
function ttsToggleBtn(){var on=ttsOn();return '<button type="button" id="voiceTtsToggle" style="margin-top:10px;padding:8px 12px;border-radius:10px;background:'+(on?'rgba(229,167,94,.2)':'#1C1F28')+';border:1px solid '+(on?'rgba(229,167,94,.45)':'rgba(255,255,255,.12)')+';color:#F2F3F7;font-size:13px;font-weight:600">'+(on?'🔊 Озвучка вкл':'🔇 Озвучка выкл')+'</button>';}
function bindTtsToggle(){var t=document.getElementById('voiceTtsToggle');if(!t)return;t.onclick=function(){setTtsOn(!ttsOn());var on=ttsOn();t.textContent=on?'🔊 Озвучка вкл':'🔇 Озвучка выкл';t.style.background=on?'rgba(229,167,94,.2)':'#1C1F28';t.style.borderColor=on?'rgba(229,167,94,.45)':'rgba(255,255,255,.12)';if(on)speak('Озвучка включена');};}
function renderVoice(){pendingStep=null;var old=document.getElementById('voiceModal');if(old)old.remove();var bg=document.createElement('div');bg.id='voiceModal';bg.style.cssText='position:fixed;inset:0;z-index:120;background:rgba(0,0,0,.62);display:flex;align-items:flex-end;justify-content:center';bg.innerHTML='<div class="voice-card" style="width:100%;max-width:520px;background:#16181F;border:1px solid rgba(255,255,255,.09);border-bottom:none;border-radius:22px 22px 0 0;padding:20px 16px calc(20px + env(safe-area-inset-bottom,0px));box-shadow:0 -8px 30px rgba(0,0,0,.45);text-align:center"><div style="display:flex;justify-content:space-between;align-items:flex-start;text-align:left"><div><div style="font-size:11px;color:#9AA0B0;text-transform:uppercase;letter-spacing:.06em">Копейка · голос</div><div style="font-size:19px;font-weight:700;margin-top:3px">Говори как удобно</div></div><button type="button" id="voiceClose" style="width:36px;height:36px;border-radius:10px;background:#1C1F28;font-size:24px;border:none;color:#F2F3F7">×</button></div><button type="button" id="voiceOrb" style="width:82px;height:82px;border-radius:50%;margin:18px auto 12px;background:linear-gradient(135deg,#F0C384,#E5A75E);display:flex;align-items:center;justify-content:center;font-size:36px;border:0;box-shadow:0 8px 28px rgba(229,167,94,.32)">🎙️</button><div id="voiceStatus" style="font-size:13px;color:#9AA0B0;min-height:20px">Слушаю…</div><div id="voiceText" style="min-height:34px;margin:8px 0;font-size:16px"></div><div style="font-size:12px;color:#9AA0B0;line-height:1.5;padding:8px">«Сигареты 100» · «сколько в подушке» · «удали последнюю» · «зарплата 4800»</div>'+ttsToggleBtn()+actionsBar('<button type="button" id="voiceAgain" style="'+btnStyle(true)+'">Говорить ещё</button><button type="button" id="voiceCancel" style="'+btnStyle(false,true)+'">Отмена</button>')+'</div>';document.body.appendChild(bg);document.getElementById('voiceClose').onclick=closeUI;document.getElementById('voiceCancel').onclick=closeUI;document.getElementById('voiceAgain').onclick=startListening;document.getElementById('voiceOrb').onclick=startListening;bindTtsToggle();bg.addEventListener('click',function(e){if(e.target===bg)closeUI();});}
function openUI(){renderVoice();startListening();}
function installMicFab(){var headerBtn=document.getElementById('btnVoice');if(headerBtn)headerBtn.style.display='none';var old=document.getElementById('voiceMicFab');if(old)old.remove();var b=document.createElement('button');b.id='voiceMicFab';b.type='button';b.title='Голосовой ввод';b.textContent='🎙️';b.style.cssText='position:fixed;right:20px;bottom:calc(80px + env(safe-area-inset-bottom,0px));z-index:61;width:44px;height:44px;border-radius:50%;background:rgba(22,24,31,.35);border:1px solid rgba(229,167,94,.35);color:rgba(242,243,247,.75);font-size:20px;display:flex;align-items:center;justify-content:center;backdrop-filter:blur(6px);-webkit-backdrop-filter:blur(6px);box-shadow:0 4px 14px rgba(0,0,0,.2);padding:0;cursor:pointer;';b.onclick=function(e){e.preventDefault();e.stopPropagation();openUI();};document.body.appendChild(b);}
function boot(){if(!document.getElementById('voiceCSS2')){var st=document.createElement('style');st.id='voiceCSS2';st.textContent='#voiceOrb.listening{animation:voicePulse2 1.1s infinite}@keyframes voicePulse2{50%{transform:scale(1.06);box-shadow:0 0 0 12px rgba(229,167,94,.12)}}#btnVoice{display:none!important}';document.head.appendChild(st);}if(window.speechSynthesis){window.speechSynthesis.getVoices();}window.kopeykaVoice={open:openUI,speak:speak,ttsOn:ttsOn,setTtsOn:setTtsOn};installMicFab();setTimeout(installMicFab,300);setTimeout(installMicFab,1000);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
