plugins {
    id 'com.android.application'
}

android {
    namespace 'app.fin.kopeyka'
    compileSdk 34

    defaultConfig {
        applicationId "app.fin.kopeyka"
        minSdk 26
        targetSdk 34
        versionCode 64
        versionName "3.9.6"
    }

    signingConfigs {
        release {
            def ks = System.getenv('FIN_KEYSTORE_PATH')
            def kp = System.getenv('FIN_KEYSTORE_PASSWORD')
            def ka = System.getenv('FIN_KEY_ALIAS')
            def kpp = System.getenv('FIN_KEY_PASSWORD')
            if (ks && kp && ka && kpp) {
                storeFile = file(ks)
                storePassword = kp
                keyAlias = ka
                keyPassword = kpp
            }
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.11.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'com.google.android.material:material:1.11.0'
}
